connections:
  database:
    - name: "Username-Password-Authentication"
      password_policy: "excellent"
      password_complexity_options:
        min_length: 6
      brute_force_protection: false

guardian:
  enabled: false

sessions:
  lifetime_in_hours: 8

tokens:
  access_token:
    lifetime_in_seconds: 3600
  refresh_token:
    lifetime_in_seconds: 86400

security:
  allowed_origins:
    - "http://localhost:3000"

passwordPolicy:
  length:
    min: 16  # This overrides hardening.yml
  history: 10
